### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by sekta2** [WEGFan/Geometry-Dash-Savefile-Editor#3]
Traceback (most recent call last):
  File "/home/misha/Geometry-Dash-Savefile-Editor-master/GDSavefileEditor.py", line 13, in <module>
    SAVE_FILE_PATH = os.path.join(os.getenv('LocalAppData'), 'GeometryDash')
  File "/usr/lib64/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

pls help

**Comment by WEGFan** [comment]
This only works on Windows since I don't know where the save is on Linux.
